#!/bin/bash
source server.conf
((`id -u` !=0 )) && echo "You need to be root to run this script!" && exit

echo "check files in ldap path: $ldap_path"
ls $ldap_path
echo "check ldap dn, user name and password: $ldap_com, $ldap_uname, *****"
grep "$ldap_uname" /etc/openldap/slapd.conf
grep "rootpw" /etc/openldap/slapd.conf

echo check mysql path: $database_path
grep datadir /etc/my.cnf
ls $database_path
echo check mysql create table and select with specified user name and password:
cat createtable | mysql -u $database_uname -p$database_passwd
echo "use school;select * from teacher;drop database school;" | mysql -u $database_uname -p$database_passwd

echo check apache rootdir and port: $apache_path, $apache_port
grep ^DocumentRoot /etc/httpd/conf/httpd.conf
grep ^Listen /etc/httpd/conf/httpd.conf
ls $apache_path
nc localhost $apache_port < ~/.bashrc 2>&1 | grep "400 Bad Request"
echo If you see "bad request", that means the port is right.

echo check samba share: Name $share_name, Path $share_path
smbclient -N -L //localhost | grep "Public samba share"

echo "check files in subversion path: $svn_path/$svn_repo"
ls $svn_path/$svn_repo
echo "you can also check svn in http://localhost:$apache_port/$svn_repo/$svn_repo"

echo "check tasks in daily cronjob. daily script(if exist):$backup_daily"
ls /etc/cron.daily/
echo "check tasks in monthly cronjob. monthly script(if exist):$backup_monthly"
ls /etc/cron.monthly/

echo Check completed!
