#!/bin/bash
#This script is used to make application.conf take effect. You need to be root to run this!
source /etc/itis/application.conf
source /etc/itis/server.conf
cache=/tmp/cache



j=0
for i in `grep -n "======" install_orangehrm2 | cut -d ":" -f1`;do
    awk "NR>$j && NR<$i" install_orangehrm2 > $cache
    nc localhost 80 < $cache | grep HTTP
    j=$i
done
sed -e "s/DBNAME/$oh_dbname/" -e "s/DBUSER/$oh_dbuser/" -e "s/DBPWD/$oh_dbpwd/" Conf.php > /usr/share/orangehrm/lib/confs/Conf.php
exit
echo "create database $oh_dbname;
create user $oh_dbuser@localhost;
update mysql.user set Password=password(\"$oh_dbpwd\") where User=\"$oh_dbuser\";
grant all privileges on $oh_dbname.* to $oh_dbuser@localhost;
flush privileges;" | mysql -u $database_uname -p$database_passwd
